#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}-{branch}'

# branches to build
branches:
  except:
    - gh-pages

# Do not build on tags
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012 R2

# fetch repository as zip archive
shallow_clone: true

cache:
  - C:\Users\appveyor\.gradle\wrapper
  - C:\Users\appveyor\.gradle\native
  - C:\Users\appveyor\.gradle\daemon
#  - C:\Users\appveyor\.gradle\caches

# environment variables
environment:
  SONATYPE_NEXUS_USERNAME:
    secure: DDwS0DjK9j/d79DuAlJy3A==
  SONATYPE_NEXUS_PASSWORD:
    secure: mr5kcUXHVYPmF+7bXPi2Ow==
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

# scripts that run after cloning repository
install:
  # Install WinPcap
  #- cmd: choco install -y winpcap

  # Install nmap which includes WinPcap instead of WinPcap itself to avoid an issue where
  # installation of autohotkey.portable which is used by choco install script for WinPcap
  # randomly fails somehow.
  - cmd: choco install -y nmap

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# scripts to run before build
#before_build:
#  - ps: if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {$env:MAVEN_PHASE = 'deploy'} else {$env:MAVEN_PHASE = 'install'}

build_script:
  # jna.nosys=true is not to use an older jna pre-installed in AppVeyor VMs.
  - cmd: gradlew.bat assemble --info --no-daemon -Djna.nosys=true -Djna.library.path=C:\Windows\System32\Npcap

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - cmd: gradlew.bat test --info --no-daemon -Djna.nosys=true -Djna.library.path=C:\Windows\System32\Npcap

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy_script:
  - ps: >-
      if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
        ./gradlew.bat uploadArchives --info --no-daemon -Psonatype_user=%SONATYPE_NEXUS_USERNAME% -Psonatype_password=%SONATYPE_NEXUS_PASSWORD%
      } else {
        echo "skipping deploy."
      }

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  - provider: Email
    to: kaitoy@pcap4j.org
    on_build_success: false
    on_build_failure: true
